version: "3"
services:
  django-bff:
    build:
      context: bff
      dockerfile: dockerfile
    volumes:
      - ./bff:/code
    ports:
      - "8000:8000"
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    build:
      context: db
      dockerfile: dockerfile
